default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: christian_construction_development

test:
  <<: *default
  database: christian_construction_test

production:
  <<: *default
  database: christian_construction
